<a href="https://colab.research.google.com/github/ash0023/DS_ML_Proj_portfolio/blob/main/Churn_modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Artificial Neural Network Proj
# Use of Theano
#Use of Tensorflow
#Use of Keras(already is collab)


In [ ]:
#!pip install theano

In [ ]:
#!pip install tensorflow

In [ ]:
#!pip install tensorflow-gpu

In [ ]:
#part 1 Data roessing

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
# Importing the dataset
dataset = pd.read_csv('/Churn_Modelling.csv')
X = dataset.iloc[:, 3: 13].values
y = dataset.iloc[:, 13].values


In [ ]:
dataset.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
dataset['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [ ]:
# Encoding categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_1.fit_transform(X[:, 2])



In [ ]:
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder='passthrough')
X= np.array(ct.fit_transform(X))
#X = ct.fit_transform(X).toarray()


In [ ]:
X=X[:,1:]

In [ ]:
print(X)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [ ]:
X_test

array([[ 1.76021608, -0.57468161, -0.55025082, ...,  0.64365658,
         0.96668786,  1.61203027],
       [-0.56811207, -0.57468161, -1.31185979, ...,  0.64365658,
        -1.03446007,  0.49626891],
       [-0.56811207,  1.74009395,  0.57157862, ...,  0.64365658,
         0.96668786, -0.42502785],
       ...,
       [-0.56811207, -0.57468161,  1.95070838, ...,  0.64365658,
        -1.03446007, -0.272747  ],
       [ 1.76021608, -0.57468161,  0.29369426, ...,  0.64365658,
        -1.03446007, -0.93306558],
       [-0.56811207, -0.57468161,  0.870047  , ..., -1.55362351,
        -1.03446007, -0.47380732]])

In [ ]:
##MAking of ANNN
##Taking keras



In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
## adding Droput for 

In [ ]:
## Initializing ANN
classifier= Sequential()

In [ ]:
## Adding the input layer  and first hidden layer
classifier.add(Dense(units= 6, kernel_initializer='uniform',activation='relu',input_dim= 11))

In [ ]:
#Adding second layer
classifier.add(Dense(units= 6, kernel_initializer='uniform',activation='relu'))

In [ ]:
##Adding output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [ ]:
#Compiling the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accruacy'])

In [ ]:
##FItting the ANN to traing se
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)  

Epoch 1/100
750/750 [==============================] - 2s 2ms/step - loss: 0.4899 - accuracy: 0.7963
Epoch 2/100
750/750 [==============================] - 2s 2ms/step - loss: 0.4273 - accuracy: 0.7963
Epoch 3/100
750/750 [==============================] - 2s 2ms/step - loss: 0.4221 - accuracy: 0.8008
Epoch 4/100
504/750 [===================>..........] - ETA: 0s - loss: 0.4179 - accuracy: 0.8216

KeyboardInterrupt: ignored

In [ ]:
# Part 3 - Making predictions and evaluating the model
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [ ]:
### Use our ANN model to predict if the customer with the following informations will leave the bank:

#  Geography: France
# - Credit Score: 600
# - Gender: Male
# - Age: 40 years old
# - Tenure: 3 years
# - Balance: $60000
# - Number of Products: 2
# - Does this customer have a credit card? Yes
# - Is this customer an Active Member: Yes
# - Estimated Salary: $50000
# - So should we say goodbye to that customer?

xnews=(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]]))
y_pred= classifier.predict(sc.transform(xnews))
y_pred=(y_pred>0.5)

In [ ]:
y_pred

array([[False]])

In [ ]:
#Evalivating,Improving and tuning ANN


In [ ]:
#Evaluvating
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():    
    classifier = Sequential()
    classifier.add(Dense(units=6 , kernel_initializer='uniform', activation='relu', input_dim=11))
    classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))
    classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return classifier

classifier= KerasClassifier(build_fn= build_classifier,batch_size= 10,nb_epoch= 100)
accuracies= cross_val_score(estimator= classifier, X=X_train,y=y_train, cv=10, n_jobs=-1)    


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  from ipykernel import kernelapp as app


In [ ]:
variance= accuracies.std()

In [ ]:
accuracies

array([0.78533334, 0.78933334, 0.80133331, 0.78933334, 0.83200002,
       0.79333335, 0.77600002, 0.80266666, 0.79733336, 0.796     ])

In [ ]:
variance

0.01407029838024023

In [ ]:
### Improving ANN
# Dropout Regularization to reduce overfitting if needed...

# importing libraries and modules...
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout


# Initializing the ANN...
classifier = Sequential()
# Adding the input layer and the first hidden layer with dropout...
classifier.add(Dense(units=6 , kernel_initializer='uniform', activation='relu', input_dim=11))
classifier.add(Dropout(rate=0.1))
# Adding the second hidden layer with dropout...
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
classifier.add(Dropout(rate=0.1))
# Adding the last and final output layer...
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))
# Compiling the ANN...
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# Tuning the ANN...



▲


SyntaxError: ignored

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):    
    classifier = Sequential()
    classifier.add(Dense(units=6 , kernel_initializer='uniform', activation='relu', input_dim=11))
    classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))
    classifier.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn=build_classifier)
parameters = {'batch_size' : [15, 25],
              'nb_epoch' : [100, 500], 
              'optimizer' : ['adam', 'rmsprop']
              }
grid_search = GridSearchCV(estimator=classifier, 
                           param_grid=parameters,
                           scoring='accuracy', 
                           cv=10)

grid_search = grid_search.fit(X_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

print(best_parameters)
print(best_accuracy)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  


NameError: ignored

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  app.launch_new_instance()


Streaming output truncated to the last 5000 lines.
Epoch 450/500
270/270 [==============================] - 1s 3ms/step - loss: 0.3966 - accuracy: 0.8348
Epoch 451/500
270/270 [==============================] - 1s 3ms/step - loss: 0.3970 - accuracy: 0.8353
Epoch 452/500
270/270 [==============================] - 1s 2ms/step - loss: 0.3970 - accuracy: 0.8350
Epoch 453/500
270/270 [==============================] - 1s 3ms/step - loss: 0.3965 - accuracy: 0.8375
Epoch 454/500
270/270 [==============================] - 1s 3ms/step - loss: 0.3968 - accuracy: 0.8363
Epoch 455/500
270/270 [==============================] - 1s 2ms/step - loss: 0.3968 - accuracy: 0.8367
Epoch 456/500
270/270 [==============================] - 1s 2ms/step - loss: 0.3965 - accuracy: 0.8345
Epoch 457/500
270/270 [==============================] - 1s 3ms/step - loss: 0.3970 - accuracy: 0.8370
Epoch 458/500
270/270 [==============================] - 1s 3ms/step - loss: 0.3967 - accuracy: 0.8364
Epoch 459/500
270/270 